### ISSUE TITLE
Geometric verification throws error when the reranking depth is large

### ISSUE THREAD

**Issue by willard-yuan** [vedaldi/visualindex#1]
Hi vedaldi,

Recently I have used the code of **visualindex** to do experiments of image retrieval, and it's really a good tutorial for me to learn the BoW model. When I set the reranking depth to a large value( less than the total number of images), it throws the following error:

``` matlab
Error using geometricVerification (line 51)
Too many outputs requested.  Most likely cause is missing [] around left hand side
that has a comma separated list expansion.

Error in picsearch_query>(parfor body) (line 56)
  [inliers, H{t}] = geometricVerification(frames, frames2{t}, matches{t}) ;

Error in picsearch_query (line 51)
parfor t = 1:depth

Error in demo_main (line 67)
    [ids, scores, result] = picsearch_query(index, queryIm,
    'geometricVerification', opts.geometricVerification) ;
```

Would you help me to fix the error?

**Comment by vedaldi** [comment]
Hi, hard to say from this information. Also, in my version line 51 of geometricVerification is a comment.

My suggestion is to use ‘dbstop on error’ in MATALB and break when the error is thrown. Then you can examine the variables etc and pinpoint the cause. You may want to replace parfor with for for this to be effective (otherwise it will break outside the parfor I think).

**Comment by willard-yuan** [comment]
Hi vedaldi,

I find the bug of it. In line 75 of `visualindex_query.m`:

``` matlab
[drop,m1,m2] = intersect(words,words2{t}) ;
```

the 'words' belongs to the query and 'words{t}' belongs to the candidates to be rerank. This line gets the intersection of 'words' and 'words{t}'. However, if the intersection is empty, i.e. 'm1' is '[]', and 'm2' is '[]', then the error throws out. I find it by setting breakpoint and running it step by step. The reRankDepth I set is 400, when the program run at t = 269, the intersection is empty. I fix it as follows:

``` matlab
parfor t = 1:depth
  % find the features that are mapped to the same visual words
  [drop,m1,m2] = intersect(words,words2{t}) ;
  if ~isempty(m1) && ~isempty(m2)
      matches{t} = [m1(:)';m2(:)'] ;

      [inliers, H{t}] = geometricVerification(frames, frames2{t}, matches{t}) ;

      if numel(inliers) >= 6
          scores(t) = scores(t) + numel(inliers) ;
      end
      matches{t} = matches{t}(:, inliers) ;
  end
end
```

I really appreciate your help.
